### ISSUE TITLE
Post install script is harmful

### ISSUE THREAD

**Issue by crubier** [tannerlinsley/react-virtual#77]
Since we installed this package, 50% of our CI/CD pipeline started failing.

The reason is that this package uses a post install script.

Here is the error which is thrown 50% of the time during `yarn install`:

```
# This file contains the result of Yarn building a package (react-virtual@virtual:02f6a86156759c9bb9f5bd96fa55ba1015b8993e779050fe9b358272baec2106973f2be4251a130e2a18a9511f3b6b721ac69018e06c8384da2a44074e767c50#npm:2.3.1)
# Script name: postinstall

UsageError: Couldn't find [38;2;215;135;95mreact-virtual[39m[38;2;135;175;255m@[39m[38;2;135;175;255mnpm:2.3.1 [02f6a][39m in the currently installed PnP map - running an install might help
    at B.findPackageLocation (/Users/vincent/Code/sterblue3/.yarn/releases/yarn-2.3.3.cjs:2:251129)
    at F.A.A.openPromise (/Users/vincent/Code/sterblue3/.yarn/releases/yarn-2.3.3.cjs:2:401596)
```

This is caused by the post install script:

```javascript
#!/usr/bin/env node

var msg = `
👩‍💻 Use react-virtual at work?
🎉 Consider sponsoring/supporting its development at:
  
  https://github.com/sponsors/tannerlinsley
`

console.log(msg)
```

Post install scripts should only be used in very specific cases, as explained here 

https://github.com/opencollective/opencollective/issues/1625 

Also, there is now first class support for package support messages, to avoid this problem:

https://github.com/nodejs/package-maintenance/blob/main/docs/PACKAGE-SUPPORT.md

I will create a MR to remove the postinstall script

**Comment by crubier** [comment]
Related: https://blog.opencollective.com/beyond-post-install/
